apiVersion: v1
kind: Service
metadata:
  name: mediintel-web
spec:
  selector:
    app: mediintel-web
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mediintel-db
spec:
  selector:
    app: mediintel-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
